name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Gatsby
      uses: jzweifel/gatsby-cli-github-action@v1.0.0
      with:
        gatsby-arg: build

    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.4
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: photography-portfolio-9a7d3
